### ISSUE TITLE
module 'yaml' missing

### ISSUE THREAD

**Issue by ajvdw** [freakent/dbus-mqtt-devices#123]
### Version

0.8.0 (current)

### VenusOS version

production, latest

### Does this issue occur during installation or at runtime ?

Runtime

### What is the issue you are actually experiencing?

when starting the application report a missing module in the log.
pip3 install pyyaml   solves the issue. This should be included in the troubleshooting paragraph of the readme

### Relevant log output

```shell
@400000006696cc1f1545f21c *** starting dbus-mqtt-devices ***
@400000006696cc20265c369c Traceback (most recent call last):
@400000006696cc20265c6194   File "/data/drivers/dbus-mqtt-devices-0.8.0/dbus_mqtt_devices.py", line 34, in <module>
@400000006696cc20265c6d4c     from device_manager import MQTTDeviceManager
@400000006696cc20265c7904   File "/data/drivers/dbus-mqtt-devices-0.8.0/device_manager.py", line 17, in <module>
@400000006696cc20265c84bc     import yaml
@400000006696cc20265c8c8c ModuleNotFoundError: No module named 'yaml'
```

**Comment by freakent** [comment]
It's in the install instructions.
